package forms;


    /*
     * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
     * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
     */

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import dao.ConnectionProvider;
import utility.BDUtility;

    /**
     *
     * @author Prathamesh Patil
     */
    public class UserRegistration extends javax.swing.JFrame {

        /**
         * Creates new form UserRegistration
         */
        public UserRegistration() {
            initComponents();
            BDUtility.setImage(this, "images/UserRegistration.jpg", 874, 650);
            this.getRootPane().setBorder(BorderFactory.createMatteBorder(4,4,4,4,Color.black));
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            btnExit = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            lbEmail = new javax.swing.JLabel();
            txtName = new javax.swing.JTextField();
            jLabel3 = new javax.swing.JLabel();
            radioMale = new javax.swing.JRadioButton();
            radioFemale = new javax.swing.JRadioButton();
            jLabel4 = new javax.swing.JLabel();
            txtEmail = new javax.swing.JTextField();
            lbContact = new javax.swing.JLabel();
            txtContact = new javax.swing.JTextField();
            lbAddress = new javax.swing.JLabel();
            txtAddress = new javax.swing.JTextField();
            txtState = new javax.swing.JTextField();
            lbState = new javax.swing.JLabel();
            lbCountry = new javax.swing.JLabel();
            txtCountry = new javax.swing.JTextField();
            jInternalFrame1 = new javax.swing.JInternalFrame();
            lblImage = new javax.swing.JLabel();
            btnRegister = new javax.swing.JButton();
            btnClear = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setMaximumSize(new java.awt.Dimension(874, 600));
            setMinimumSize(new java.awt.Dimension(874, 600));
            setUndecorated(true);

            btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            btnExit.setText("X");
            btnExit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnExitActionPerformed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            jLabel1.setText("User Registration");

            lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbEmail.setText("Email");

            txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

            jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel3.setText("Gender");

            radioMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            radioMale.setText("Male");
            radioMale.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    radioMaleItemStateChanged(evt);
                }
            });
            radioMale.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    radioMaleActionPerformed(evt);
                }
            });

            radioFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            radioFemale.setText("Female");
            radioFemale.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    radioFemaleItemStateChanged(evt);
                }
            });
            radioFemale.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    radioFemaleActionPerformed(evt);
                }
            });

            jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel4.setText("Name");

            txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

            lbContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbContact.setText("Contact");

            txtContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

            lbAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbAddress.setText("Address");

            txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

            txtState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

            lbState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbState.setText("State");

            lbCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbCountry.setText("Country");

            txtCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

            jInternalFrame1.setVisible(true);

            lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lblImageMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
            jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
            jInternalFrame1Layout.setHorizontalGroup(
                    jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
            );
            jInternalFrame1Layout.setVerticalGroup(
                    jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
            );

            btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            btnRegister.setText("Register");
            btnRegister.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnRegisterActionPerformed(evt);
                }
            });

            btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            btnClear.setText("Clear");
            btnClear.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnClearActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(radioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(radioFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                            .addComponent(lbContact, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addGap(18, 18, 18)
                                                                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                    .addComponent(lbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                    .addComponent(lbState, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addGap(18, 18, 18)
                                                                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(lbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGap(84, 84, 84)
                                                                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(58, 58, 58)
                                                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(29, 29, 29))))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(289, 289, 289)
                                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(16, 16, 16))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(36, 36, 36)
                                                    .addComponent(jLabel1)))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel4))
                                                    .addGap(25, 25, 25)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel3)
                                                            .addComponent(radioMale)
                                                            .addComponent(radioFemale))
                                                    .addGap(25, 25, 25)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbEmail))
                                                    .addGap(25, 25, 25)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbContact))
                                                    .addGap(25, 25, 25)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbAddress))
                                                    .addGap(25, 25, 25)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbState))
                                                    .addGap(25, 25, 25)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbCountry)))
                                            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnRegister)
                                            .addComponent(btnClear))
                                    .addContainerGap(88, Short.MAX_VALUE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>

        private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
            this.dispose();
        }

        private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }
        BufferedImage originalImage = null;
        File selectedFile = null;
        private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(this);
            if(result == JFileChooser.APPROVE_OPTION){
                selectedFile = fileChooser.getSelectedFile();
                try{
                    originalImage = ImageIO.read(selectedFile);
                    int originalWidth =originalImage.getWidth();
                    int originalHeight =originalImage.getHeight();

                    int labelWidth = lblImage.getWidth();
                    int labelHeight = lblImage.getHeight();

                    double scaleX =(double) labelWidth / originalWidth;
                    double scaleY =(double) labelHeight / originalHeight;

                    double scale = Math.min(scaleX, scaleY);

                    int scaledWidth = (int)(originalWidth * scale);
                    int scaledHeight= (int)(originalHeight * scale);

                    Image scaledImage = originalImage.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(scaledImage);
                    lblImage.setIcon(icon);



                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }


        }

        private void radioMaleItemStateChanged(java.awt.event.ItemEvent evt) {
            if(radioMale.isSelected()){
                radioFemale.setSelected(false);
            }
        }

        private void radioFemaleItemStateChanged(java.awt.event.ItemEvent evt) {
            if(radioFemale.isSelected()){
                radioMale.setSelected(false);
            }
        }

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
            clearForm();
        }

        private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {
            try{
                String name = txtName.getText().toString();
                String gender = "";
                if(radioMale.isSelected()){
                    gender = "Male";
                }else if(radioFemale.isSelected()){
                    gender = "Female";

                }
                String email = txtEmail.getText().toString();
                String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9+_.-]+$";
                if(!email.matches(emailRegex)){
                    JOptionPane.showMessageDialog(null, "Invalid Email","Invalid",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                String contact = txtContact.getText().toString();
                String contactRegex = "^\\d{10}$";
                if(!contact.matches(contactRegex)){
                    JOptionPane.showMessageDialog(null, "Invalid Contact number","Invalid",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                String address = txtAddress.getText().toString();
                String state = txtState.getText().toString();
                String country = txtCountry.getText().toString();
                String uniqueRegId = ""+System.nanoTime()+System.nanoTime()+System.nanoTime()+System.nanoTime();

                if(name.isEmpty() || email.isBlank() || contact.isEmpty()|| address.isEmpty()|| state.isEmpty()||country.isEmpty() || uniqueRegId.isEmpty() || gender.isEmpty() ){
                    JOptionPane.showMessageDialog(null, "One or more fields are empty. ","Field Empty", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                Connection connection = ConnectionProvider.getcon();
                try {
                    Statement st = connection.createStatement();
                    ResultSet rs = st.executeQuery("select * from userdetails where email ='"+email.trim() +"'");
                    if(rs.next()) {
                        JOptionPane.showMessageDialog(null,"Duplicate email.","Duplicate",JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }catch(Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null,ex);
                }




                String imageName = saveImage(email);
                String insertQuery = "INSERT into userdetails(name,gender,email,contact,address,state,country,uniqueRegid," +
                        "imagename) VALUES(?,?,?,?,?,?,?,?,?)";
                PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);

                preparedStatement.setString(1, name);
                preparedStatement.setString(2, gender);
                preparedStatement.setString(3, email);
                preparedStatement.setString(4, contact);
                preparedStatement.setString(5, address);
                preparedStatement.setString(6, state);
                preparedStatement.setString(7, country);
                preparedStatement.setString(8, uniqueRegId);
                preparedStatement.setString(9, imageName);

                preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(null,"User Register Successfully");
                clearForm();






            }catch(Exception ex){
                ex.printStackTrace();
            }
        }

        private String saveImage(String email){
            if(originalImage!= null && selectedFile != null){
                try{
                    String savePath = BDUtility.getPath("Images\\");
                    String extension = BDUtility.getFileExtension(selectedFile.getName());
                    String imageName = email+"."+extension;
                    File saveFile = new File(savePath+imageName);
                    BufferedImage scaledImage  = BDUtility.scaleImage(originalImage, ImageIO.read(selectedFile));
                    ImageIO.write(scaledImage, extension,saveFile);
                    return imageName;


                }catch(Exception ex){
                    ex.printStackTrace();

                }
            }
            return null;
        }


        private void clearForm(){
            txtName.setText("");
            txtEmail.setText("");
            txtContact.setText("");
            txtAddress.setText("");
            txtState.setText("");
            txtCountry.setText("");
            radioMale.setSelected(false);
            radioFemale.setSelected(false);
            lblImage.setIcon(null);
        }
        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new UserRegistration().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnExit;
        private javax.swing.JButton btnRegister;
        private javax.swing.JInternalFrame jInternalFrame1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel lbAddress;
        private javax.swing.JLabel lbContact;
        private javax.swing.JLabel lbCountry;
        private javax.swing.JLabel lbEmail;
        private javax.swing.JLabel lbState;
        private javax.swing.JLabel lblImage;
        private javax.swing.JRadioButton radioFemale;
        private javax.swing.JRadioButton radioMale;
        private javax.swing.JTextField txtAddress;
        private javax.swing.JTextField txtContact;
        private javax.swing.JTextField txtCountry;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtName;
        private javax.swing.JTextField txtState;
        // End of variables declaration
    }

